### ISSUE TITLE
Broken share buttons

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#10]
The share button on the https://kefwmag.github.io/tech/2016/01/26/technology-post-1.html page yields a fairly dodgy looking link, considering it is missing the kefwmag.github.io domain: `/tech/2016/01/26/technology-post-1.html`

Can this be fixed?

**Comment by ChilliByte** [comment]
Wow great minds think alike I was literally writing up this issue. The Google+ and Facebook ones seem to be 100% broken for now, twitter fix for your outlined issue is coming next commit

**Comment by ChilliByte** [comment]
All Fixed

**Comment by benjimarshall** [comment]
Good job
