### ISSUE TITLE
Improve Reading Layout

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#12]
The current fullscreen article layout is difficult to read. Perhaps something more akin to [mic.com](http://mic.com)'s layout would look more professional on the big screen?

**Comment by ChilliByte** [comment]
Added padding and increased h1 size

**Comment by benjimarshall** [comment]
@ChilliByte The adjustments to h1 on the article overview pages are not good, the font is much too large
