### ISSUE TITLE
Make site work on mobiles

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#13]
The site needs a meta viewport tag. And maybe some CSS tweaks?

**Comment by benjimarshall** [comment]
It seems particularly bad on phablet's which tend to render it as a desktop site with tiny text

**Comment by ir-g** [comment]
All mobiles render it like that. It seems to needs some additional CSS, and
a meta viewport tag

**Comment by benjimarshall** [comment]
@isaacrg Could you have a close look at the padding? Its [a bit excessive for me](http://imgur.com/Y4WpSb8).

**Comment by ir-g** [comment]
I have filed a fix. Does it work now?

**Comment by benjimarshall** [comment]
That's much better. This seems to be sorted as far as I can see

**Comment by benjimarshall** [comment]
Right, it still seems quite wonky: I've moved the site from `dindex.html` to `index.html` but that shouldn't mean too much I don't think. The "Read more" buttons and padding seems to be off: [here](http://imgur.com/a/k1NYV)

**Comment by benjimarshall** [comment]
@isaacrg @ChilliByte ???

**Comment by ir-g** [comment]
@benjimarshall I dont think that is your fault, but by goodness does that look ugly

**Comment by benjimarshall** [comment]
@isaacrg The "Read more" buttons all seem to be much better, so thank you for that. Padding still seems to be an issue both on [desktop ](http://imgur.com/DpuzAiq) and on [mobile](http://imgur.com/SleKpOZ).

**Comment by ir-g** [comment]
@benjimarshall I will direct this issue towards @ChilliByte - He understands the code far better than I do (he wrote it, I didn't!), so will likely be able to resolve padding issues more easily.

**Todo:**
- [ ] Fix desktop padding ([Preview](http://i.imgur.com/DpuzAiq.png))
- [ ] Fix mobile padding ([Preview](http://i.imgur.com/SleKpOZ.png))

**Comment by ChilliByte** [comment]
the padding issues are def. temporary, if possible I ask you remove any edits (I am aware they look horrible, they are being fixed) This will be fixed ASAP, after I finish the desktop site

**Comment by benjimarshall** [comment]
Should you pair instead sit down and talk through the edits, instead essentially deleting already completed work? I get that both of you dislike each other's code but would it be possible to explain your bits to each other, @isaacrg, @ChilliByte?

**Comment by ir-g** [comment]
@benjimarshall Don't worry, we have spoken - Deep will make changes to the
existing set, just don't make _any_ changes whatsoever. Deep plans on
rolling a fix tomorrow.

**Comment by ChilliByte** [comment]
are these issues now fixed?

**Comment by benjimarshall** [comment]
Well, the padding is. You've broken the word "Home" on the homepage but all of the other titles like "News" are fine

**Comment by benjimarshall** [comment]
@ChilliByte OK that looks good for now
