### ISSUE TITLE
Delete Redundant Files

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#23]
there are many unused unnecessary files remaining in the repo that are > 2 months old, I would silently have deleted them but I dont want to break anything, so could someone please go through the repo deleting anything unnecessary?

**Comment by ChilliByte** [comment]
well i got a lot of fucking help with this

**Comment by ChilliByte** [comment]
sorry for salt

**Comment by ir-g** [comment]
@ChilliByte The folder called CSS can go. Also - rename the folder called deep, and the layout references to it.

**Comment by ChilliByte** [comment]
no need to rename thats too much effort seeing as I dont know how many times its been referenced

**Comment by ir-g** [comment]
I'll sort that one tomorrow then - alongside removing any old unused JS files

**Comment by ir-g** [comment]
I think that's us sorted - I've modified the layout and the @benjimarshall has deleted the countdown stuff.
