### ISSUE TITLE
Copyright/Creator Mark?

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#24]
Should there be a small amount of text somewhere on the layout stating when the site was created, and who by, or would that be inappropriate?

The text would be something along the lines of

BackChat &copy; [KEFW](//kefw.org) 2016. Website made with <3 By [Deep Sohelia](//chillibyte.github.io) and [Isaac Reid-Guest](//ir-g.uk). Backend written by Benji Marshall, [Matt Randell](//hexaglow.com) and [Isaac Reid-Guest](//ir-g.uk), using [Jekyll](/jekyllrb.com)

**Comment by ChilliByte** [comment]
will add temporarily to test css, but can remove if others deem it innappropriate

**Comment by benjimarshall** [comment]
Looks good, and the general idea is good, though I'm not super comfortable with the heart but that probably is just me. As with all things with this project, [it renders badly on mobile](http://imgur.com/OO3zxti)

**Comment by ir-g** [comment]
Concerning the copyright, would that not surely remain with the respective authors? If so, then "All Rights Reserved" might make more sense.

**Comment by ChilliByte** [comment]
I literally have no clue how copyrights work I just made some BS up, if you're more familiar with how this all works then just edit/comment what you think it should say and I'll or someone else'll change it

**Comment by ChilliByte** [comment]
Issue still needed?

**Comment by ir-g** [comment]
No, we should be good to close this.
