### ISSUE TITLE
Add the logo in the top right corner

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#27]
Each section will have a different logo, I will be making those logos over the next day or so

**Comment by ChilliByte** [comment]
is this a good idea? personally I think it might look a little bodged and tacky

**Comment by ir-g** [comment]
I'm with @ChilliByte - There is no reason to add the logo, and it wouldn't make any design sense - particularly with the section-coloured headers

**Comment by ChilliByte** [comment]
plus, the logo is already visible in the favicon

**Comment by ChilliByte** [comment]
would a watermark in the lower right hand corner look better?

**Comment by benjimarshall** [comment]
@ChilliByte Give it a try, and we can roll it back if it looks bad

**Comment by ChilliByte** [comment]
okie kokie

**Comment by ChilliByte** [comment]
added

**Comment by ir-g** [comment]
@benjimarshall Thoughts on the current look?

**Comment by benjimarshall** [comment]
Looks good. It can get entirely lost on mobile but at least it doesn't spectacularly break anything.

**Comment by ir-g** [comment]
Yeah... Also, if any more menu options are added, we are going to want to re-write the whole menu setup.
