### ISSUE TITLE
Add an Agony Aunt Section

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#28]
Add an Agony Aunt Section, colours tbc

**Comment by ChilliByte** [comment]
how will this work?

**Comment by benjimarshall** [comment]
Simple another category like "Sports" or "News" or whatever

**Comment by ir-g** [comment]
Errmmmm Not so simple. Also, name the colours

**Comment by benjimarshall** [comment]
A brightish pink around the #ff33ff mark

**Comment by benjimarshall** [comment]
Also, why isn't it very simple?

**Comment by ir-g** [comment]
We have currently have to manually make the CSS customisations for each
section, add in a category new page, and we need a good idea of what it
will be displayed as, on the site.

**Comment by ir-g** [comment]
Also, give us _both_ colours you want us to use

**Comment by benjimarshall** [comment]
We could make it better, but its probably more effort than its worth. #e614e6 for the darker one and #ff50ff for the lighter one

**Comment by ir-g** [comment]
Ok, I'll get to it.

**Comment by ChilliByte** [comment]
for clarification, will there be a form to submit stuff or will these just be a new type of post?

**Comment by ChilliByte** [comment]
also, fixing colors

**Comment by ir-g** [comment]
Awesome -- I'm not sure what colours would suit it

**Comment by ChilliByte** [comment]
colours fixed, #f55 and #f99 were chosen by others

**Comment by ChilliByte** [comment]
issue still needed?

**Comment by ir-g** [comment]
I don't think so. All seems good.
