### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#3]
A favicon for the site

**Comment by ChilliByte** [comment]
Template Favicon Added, Please update favicon.ico when a new design is required

Favicon Image File requirements:
Filename: favicon.ico
Location: /
Size: 32x32

**Comment by benjimarshall** [comment]
Can we make the white bit of the Favicon transparent?

**Comment by ChilliByte** [comment]
We need an actual favicon image, properly aligned with transparency, then upload that, I dont have anything to edit images with.

**Comment by ChilliByte** [comment]
yay misclicks

**Comment by ChilliByte** [comment]
Resolved, @benjimarshall ?

**Comment by benjimarshall** [comment]
Nope, the next _fun_ job is to have a different favicon colour for each page... I need to pin Kane down to get an original file for me to work with. Don't worry too much for now

**Comment by ChilliByte** [comment]
Implemented. see /assets/favicons/
