### ISSUE TITLE
Edition 1 article upload

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#30]
Currently waiting on final edits from staff and opinions of leadership

**Comment by ChilliByte** [comment]
added a few, without images

**Comment by ir-g** [comment]
@benjimarshall Is this now complete?

**Comment by benjimarshall** [comment]
Lol no. I'll email you the current, slightly out of date PDF that we are working to

**Comment by ir-g** [comment]
@benjimarshall Thanks.

**Comment by benjimarshall** [comment]
I'll work from the back, Deep so far has worked from the front, I'll leave you pair to negotiate if or what you do

**Comment by ChilliByte** [comment]
we need to upload images, @isaacrg could do that?

**Comment by benjimarshall** [comment]
Nope, we need the InDesign files from Ciaran who is out. I'll sort that tomorrow, let's just get the text up

**Comment by ir-g** [comment]
I'll do the ama's if you like? Should Ama's be one article for each edition
or separate?

**Comment by benjimarshall** [comment]
I've nearly finished them, I didn't notice till now. I was doing them as separate articles though I have come to regret that decision

**Comment by ir-g** [comment]
If you've started, then go right ahead on them, I would recommend a single post, thought that is up to you, though once we have started with a style, we may well want to continue it.

**Comment by benjimarshall** [comment]
UPDATE: I've added all the articles except the Oscars ones because they look like a pain in the backside. I'll get to those tomorrow

**Comment by ChilliByte** [comment]
@benjimarshall I saw them and said lol nope, anything I can do to help?

**Comment by benjimarshall** [comment]
Not at the moment. We might have a _super fun_ image upload-athon tomorrow afternoon, but not for now. 

With the Oscars ones, I'm going to whinge and we'll come up with a plan

**Comment by ir-g** [comment]
Do we just need to put the images into the articles now?

**Comment by ChilliByte** [comment]
@isaacrg Yes, except for 1 particularly annoying article

**Comment by benjimarshall** [comment]
Finally done
