### ISSUE TITLE
Find way of linking submit form to ama section

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#32]
The submit form can be linked in an article with a simple &lt;a> tag:

`<a href = "/ama/submit"> Message us! </a>
`
etc etc, however, this may not be the best way, and an alternative may be wanted. 
If an alternative is not necessary, then an button to add this to the article needs to be added to /format.html

**Comment by benjimarshall** [comment]
We could have a final boilerplate paragraph with a link, asking them to email us. The link could go to a a page very similar to the contact page. I'll chat to Ciaran to see if they want it to go to another email address.

**Comment by ChilliByte** [comment]
the submit form is already set up

**Comment by ChilliByte** [comment]
http://backchat.kefw.org/ama/submit/

**Comment by benjimarshall** [comment]
Well, that the bottom of each article we could have a line saying: "Submit your letters to Mel and Ma _here_"

**Comment by ir-g** [comment]
Or that banner/tagline could be automatically placed at the top or bottom of all
ama posts?

**Comment by benjimarshall** [comment]
If you can, sure. It seems like a lot of effort since we can just copy and paste that sentence into each article.

**Comment by ChilliByte** [comment]
if we put it at the top we f**k up the extract/excerpt system

**Comment by ir-g** [comment]
I can add the the tagline in very easily - I'll have a test now.

**Comment by ir-g** [comment]
@ChilliByte Duly noted. I'll put them at the bottom, but holding off due to #33.

**Comment by ChilliByte** [comment]
@isaacrg Worth noting that the excerpt system uses the first paragraph of the post, if you're not actually editing the posts, then at the top is fine

**Comment by ir-g** [comment]
@ChilliByte Ok, cool, do you have a preference for it to be at the top or the bottom?

**Comment by ChilliByte** [comment]
@isaacrg I think it'd be less likely to be ignored at the top

**Comment by ir-g** [comment]
@ChilliByte Ok, cool

**Comment by ir-g** [comment]
Also, @benjimarshall your thoughts?

**Comment by ChilliByte** [comment]
@isaacrg See #40

**Comment by ir-g** [comment]
Given #40,  this is sorted. :)
