### ISSUE TITLE
Crazy commit

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#33]
@benjimarshall's commit 7b2dc6241be1cbf3a9239d6af9afe151c6725426 has some messy, non-extensioned files, and some unexplained behaviour... Whats up?

**Comment by ir-g** [comment]
I'm of course guessing this is linked to #30

**Comment by ChilliByte** [comment]
wtf happened? XD

**Comment by ir-g** [comment]
~~F*ck knows.~~ @benjimarshall might know.

**Comment by ChilliByte** [comment]
GH Status is all ok https://status.github.com/

**Comment by ir-g** [comment]
Yep, I think @benjimarshall has sent in a broken merge maybe.

**Comment by benjimarshall** [comment]
I know. Git cannot revert due to the special characters (a question mark) in one of the names. We're just going to need to remake the files. We has successfully broken Git, I will be looking into it later tonight and potentially be firing an issue off to Git themselves

**Comment by ChilliByte** [comment]
are we 100% certain its the softwares fault and one of us just didnt do something stupid? for software that widely used I wouldve thought they wouldve sorted that stuff...

**Comment by ChilliByte** [comment]
Is everyone everywhere on Git f**cked then? Because special characters are unavoidable.

**Comment by benjimarshall** [comment]
70% It's not our fault. The error message I'm getting `The following untracked working tree files would be overwritten by merge` should appear when the files are present, but they are not

**Comment by benjimarshall** [comment]
Right, back to as it was an hour ago: everyone can edit, be very careful when messing with reverts and checkouts for before today

**Comment by ir-g** [comment]
@benjimarshall  FYI, use the Github web interface for non-development edits. It serves as a safer platform for commits, doesn't induce merges, and is far more trustworthy. Also, special characters have a track record of being better within Github web(though not perfect), as Windows and CMD both have their own special character setups that may be interfering with Git's own ability to read files.

**Comment by benjimarshall** [comment]
@isaacrg That might be it, but any high-powered git features such as revert or checkout (to change undo merge) are not available online. By using the online environment which doesn't complain when it ought to (such as a question mark in a file name, which is an all round terrible idea because of its wildcard properties), you may just be sowing issues which we the reap later

**Comment by benjimarshall** [comment]
https://josephscott.org/archives/2007/02/things-that-shouldnt-be-in-file-names-for-1000-alex/

**Comment by benjimarshall** [comment]
Right, now that the special characters have been removed online, my git repo on my laptop is now happy

**Comment by ChilliByte** [comment]
when removing characters from filenames just make sure you dont break things

**Comment by benjimarshall** [comment]
AFAIK I don't think we have

**Comment by benjimarshall** [comment]
@isaacrg @ChilliByte  It's 95% the GitHub Web Interfaces fault for absolutely [no input validation](https://github.com/benjimarshall/special-characters), 2% Git's fault for handling stupid files stupidly, and 3% my fault for letting it run riot. I'm off to make an issue with GH themselves

**Comment by ChilliByte** [comment]
can we do a lil bit of cheeky xss with the file name box?

**Comment by ir-g** [comment]
I doubt it, but that would be fun...
