### ISSUE TITLE
Author naming

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#34]
In post author sections, it shows their respective titles. Should that happen, given that titles will change over time?

eg: `Kane Ogier - Arts and Entertainment Editor`

Also, there appear to be **two** people using the title _Arts and Entertainment Editor_

**Comment by ChilliByte** [comment]
These are simply and copy and pasted from the printed copy, not our decision

**Comment by ChilliByte** [comment]
and yes there are 2

**Comment by ir-g** [comment]
@ChilliByte OK, awesome.

**Comment by ir-g** [comment]
@benjimarshall Thoughts?
