### ISSUE TITLE
Edition 1: Get the images

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#38]
Please can we get all the edition 1 images and put them in their own special folder. (I know there is a hold up atm, but the issue is there just to keep an eye on it...

**Comment by ChilliByte** [comment]
the folder for all images is /assets
we can either dump all the images in there, or dump them in a sub folder for each edition

**Comment by benjimarshall** [comment]
I'm going to look into Git LFS for the butt-ton of images. I'll get back to you on that

**Comment by benjimarshall** [comment]
Got them all, some with better names than others

**Comment by ir-g** [comment]
Brilliant - FYI try to name future folders as `assets/edition-2/`, as opposed to using caps or spaces, just for URL safety.

Also, @benjimarshall, what are your thoughts on Git LFS?

**Comment by benjimarshall** [comment]
I will, and I will be moving to `assets/edition-1/` when it's all calmed down. 

Git LFS seems to be best suited for unthinkably large files, think textures, `.psd` files, chunks of audio. It isn't particularly necessary for small 500 KB images, and can be a bit of faff

**Comment by ir-g** [comment]
Good to hear, I am always ready to help where possible.

Yeah, I thought that might be the case when I first saw LFS some months
back - Git is honestly not the greatest for assets, etc but makes sense in
this situation. Also, how big is the image folder in size roughly?

**Comment by benjimarshall** [comment]
@isaacrg 32.2 MB for 88 images, about 350 KB per image on average

**Comment by ir-g** [comment]
OK, cool. We won't hit a gig anytime soon then, so we should be good.
