### ISSUE TITLE
Fix AMA excerpts

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#40]
All the excerpts for the AMA sections are "Mel and Ma" 

Maybe add "Dear Mel and Ma" to the top insert, and remove that line from each post?
Related: #32

**Comment by ChilliByte** [comment]
#32

**Comment by ir-g** [comment]
Potentially, though this works on the basis of the ama team never changing. How about we see if we can swap the excerpt with a custom description on the listing pages?

**Comment by ChilliByte** [comment]
"Mel and Ma" is a pseudonym, it isnt even close to the names of the real people, i dont thing thats worth doing, @isaacrg

**Comment by ir-g** [comment]
Fair enough then, I'll get to it!

**Comment by ChilliByte** [comment]
@isaacrg can you make the "Dear Mel & Ma" in normal plain text

**Comment by ir-g** [comment]
Will do.
