### ISSUE TITLE
Article mis-sizing on mobiles

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#41]
Re: #40 (Broken ama excerpts)

Articles with smaller/title excerpt combinations don't follow a standard size on some mobile devices.

https://imgur.com/U5qc0vm

**Comment by benjimarshall** [comment]
Haven't got a clue. Thoughts, @ChilliByte?

**Comment by ChilliByte** [comment]
Missing Width Statement in Mobile Media Query CSS. Will fix ASAP

**Comment by ir-g** [comment]
Brilliant, thanks!
