### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#44]
Add Easter Eggs to the code in comments if you want

**Comment by ir-g** [comment]
Also, maybe konami code could trigger a page which has wilko in various political campaign posters?

**Comment by ir-g** [comment]
@ChilliByte This could incorporate the old hope poster

**Comment by ChilliByte** [comment]
I think the easter eggs should be unobtrusive seeing as its not for us, if you will. Code comments dont really effect page load times, whereas the konami code will, and extra pages etc will make build times bigger, no?

**Comment by ir-g** [comment]
Build times shouldn't be a large concern(even with tons of posts, the site should continue to build in under half a second), but obviously konami code requires JS usage, which obviously increases page load times.

**Comment by ChilliByte** [comment]
I've put a few little jokes in my css code, though I'll add more as time goes by

**Comment by ChilliByte** [comment]
most of these will be in #57
