### ISSUE TITLE
Rename terrible image names

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#45]
Rename terrible image names from Ciaran

**Comment by ir-g** [comment]
@benjimarshall  Loving the commit messages :)

**Comment by benjimarshall** [comment]
Thanks, I'm trying to combat the boredom...

**Comment by ChilliByte** [comment]
are these done?

**Comment by benjimarshall** [comment]
@ChilliByte Not yet. I still need to do the Oscars article then I'll delete the superfluous images

**Comment by ir-g** [comment]
@benjimarshall For the sake of archival purposes I wouldn't recommend deleting any of the images.

**Comment by ir-g** [comment]
@benjimarshall What is the status of this?

**Comment by benjimarshall** [comment]
I'm going to move the redundant images over to a folder for them, and then we'll be done

**Comment by ir-g** [comment]
Awesome - If the folder was `/assets/edition-1/redundant`, or similar that would probably be best. This isnt directly linked to the official release, so I'll move it off that milestone.

**Comment by ChilliByte** [comment]
Is this done?

**Comment by ChilliByte** [comment]
how about now?

**Comment by benjimarshall** [comment]
Yup
