### ISSUE TITLE
Rename image folder

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#46]
Rename `assets/Edition 1/` to `assets/edition-1/` when all the articles are sorted.

**Comment by ir-g** [comment]
I have created a copy of `assets/Edition 1/` at `assets/edition-1/`, so that article images can be moved over gradually.

**Comment by ChilliByte** [comment]
@isaacrg can we make all references to `assets/Edition 1/` automagically go over to `assets/edition-1/` so we dont have to go through every article?

**Comment by ir-g** [comment]
Sadly, no.

**Comment by benjimarshall** [comment]
Done
