### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#48]
This is the Golden Globes fashion article, and all of the images are essentially, and it looks terrible. Any ideas?

[this](http://backchat.kefw.org/arts/2016/04/21/the-golden-globes.html) (whoops sorry for the local host)

**Comment by benjimarshall** [comment]
Also, @ChilliByte can you do any date magic if needed on this file?

**Comment by ir-g** [comment]
Hmm. On mobile the images are far smaller and the article doesn't look bad,
but the images start going far below the matching text.

**Comment by benjimarshall** [comment]
Yeah that's the problem in all sizes

**Comment by ir-g** [comment]
A table might solve that...

**Comment by benjimarshall** [comment]
@isaacrg Have a play, and we can revert it if you break anything

**Comment by ChilliByte** [comment]
a local host link. really.

**Comment by ChilliByte** [comment]
@benjimarshall use the "description" feature of the image embedding. this is sort of what it was designed for

**Comment by ChilliByte** [comment]
@isaacrg NO NO TABLES

**Comment by ir-g** [comment]
1. A real link http://backchat.kefw.org/arts/2016/04/21/the-golden-globes.html
2. +1 for descriptions, though idk how that would turn out.
3.  I know, I know. We really need an image gallery doodah...

**Comment by ChilliByte** [comment]
can we have more than 1 image.html? so we can have full width image?

**Comment by ir-g** [comment]
Sure

**Comment by ChilliByte** [comment]
@benjimarshall has there been any more work on this?

**Comment by benjimarshall** [comment]
@ChilliByte Not yet. The current image include is found [here](https://github.com/Kefwmag/kefwmag.github.io/blob/master/_includes/image.html). I could make a second, similar file but with a CSS class attribute to the `<img>` tag if that would help?

**Comment by ChilliByte** [comment]
I could do that too its just I dont know how else to show the images, i dont know what else would look good

**Comment by benjimarshall** [comment]
Seems done now
