### ISSUE TITLE
/format.html filename fix

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#50]
For the /format.html generator, the file name generator needs to:
- [x] Block repeated dashes (ie: `2016-04-21-my-sport--ravi-gurung.md` becomes `2016-04-21-my-sport-ravi-gurung.md`
- [x] Only contain the characters a-z, 0-9, dashes and one dot(for .md, ofc)
- [x] Make all output lowercase.

**Comment by ChilliByte** [comment]
the last two make sense, but i dont understand the need for the first

**Comment by ChilliByte** [comment]
eh whatever its 1 am fuck it, next commit

**Comment by ir-g** [comment]
@ChilliByte The first one is just a logical measure for good urls, and because otherwise I'll obsess over renaming them later.

**Comment by ChilliByte** [comment]
@isaacrg Can you give it a test? I've written the regex myself for the first time and I dont trust it.

(Well I've written regext before but that was just matching one character and its piss, this is more complex)

**Comment by ir-g** [comment]
All seems to work well as expected, though I think maybe we should require the user to pick a date
