### ISSUE TITLE
CSS Clean up

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#52]
The css I wrote was a bit sort of "chuck this rule in, see what happens". I need to structure, comment, and clean up my code, as well as split it up into multiple files.
- [x] Comment Stylesheets
- [x] Move to `/css/` 
- [x] Split into relevant files (themes, mobiles, desktop, tablet etc)
- [x] Order correctly 
- [x] Check for, and if necessary, remove redundant lines 

Isaac, Benji, Matt, you dont have to do anything unless I mess something up, this is just for my reference.

**Comment by ChilliByte** [comment]
@isaacrg @benjimarshall Better? Did I break anything?

**Comment by ir-g** [comment]
@ChilliByte Things look good, still seem to be working. :smiley:
