### ISSUE TITLE
Does _config.yml need updating?

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#54]
_config.yml has email and url fields. do these need updating?

**Comment by benjimarshall** [comment]
Email: At the moment, no, because we are not using it. We could use it in the site, I'll have a look at some point.

URL: YES THIS IS RIGHT DON'T TOUCH IT OR IT'LL BREAK

**Comment by ir-g** [comment]
@benjimarshall @ChilliByte The email value is one that isn't a pre-defined variable - ie. This one has no pre-assigned purpose, so we can do as we like with it. - I'd recommend hooking it up to the formspree forms, and anywhere else we mention the email address.

But **do** update the email value on the `_config.yml` first, ofc.

**Comment by ir-g** [comment]
We no longer need this issue. The config is all good, it seems.
