### ISSUE TITLE
Unbreak the site

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#55]
Nearer release time, move index2 over to index

**Comment by ir-g** [comment]
@benjimarshall Just so that no mess-ups occur, can the site be unbroken at ~15:00 or ~16:00 today?

**Comment by ChilliByte** [comment]
@isaacrg why is this needed? its just renaming a file

**Comment by ir-g** [comment]
@ChilliByte I know, but sometimes Github page builds don't go through for some time - international cache servers sometimes take while to be updated.

**Comment by ChilliByte** [comment]
ah, i understand
