### ISSUE TITLE
Filter By Author?

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#58]
Is it possible to get Jekyll to generate pages for each author with their own articles on?

**Comment by benjimarshall** [comment]
Definitely possible. I'll look into this tomorrow

**Comment by ChilliByte** [comment]
ty

**Comment by ChilliByte** [comment]
While @benjimarshall is away I've looked around, this is v. easy to do with a custom "author.html" for each author, then just use liquid fors and conditionals to build their page.

This is definetely the easiest way to go.
Is it the most sustainable?
Is it the most elegant?

**Comment by ChilliByte** [comment]
http://backchat.kefw.org/author/ciaran-hanvey/
I DID EET

This system requires a seperate index.html per author (only 5 lines of front matter to be fair, no html)

**Comment by ir-g** [comment]
Use Jekyll collections for this. I'll help out, but that is exactly what should be used.

**Comment by ir-g** [comment]
Re: #61

**Comment by ChilliByte** [comment]
@isaacrg are jekyll collections what is used for the categories? bc I've essentially used the same code for the categories that i have for the author (legit just changed `{{page.category}}` to `{{page.author}}`

**Comment by ir-g** [comment]
Not quite, but it isn't dissimilar

**Comment by ChilliByte** [comment]
@isaacrg What should I be doing then, because a page per author doesnt seem sustainable

**Comment by ir-g** [comment]
A page per author might be reasonable...
