### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#6]
Make sure that images in the article are stable

**Comment by benjimarshall** [comment]
@ChilliByte @isaacrg  what on earth is going on with your image handling, Deep? Can we try to implement some kind of image scaling, but more importantly images that don't nuke the text underneath (try using Find for something like "ipsum", the words are very definitely there, just hidden)

**Comment by ir-g** [comment]
@benjimarshall Eek. I don't quite know what happening here. Playing in dev tools isn't helping unusually - @ChilliByte needs to check through the theme code.

**Comment by ChilliByte** [comment]
Image code wasnt broken, was never added. Sizing rules added to /deep/style.css

WARNING: FIRST PARAGRAPH OF AN ATRICLE IS WHAT IS DISPLAYED ON THE PREVIEW PAGE, AND THIS CANNOT BE AN IMAGE. THIS IS NOT THE FAULT OF MY CSS. THIS IS JEKYLL.

**Comment by ir-g** [comment]
@ChilliByte How is this Jekyll's fault, out of interest?
