### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#60]
God knows how to implement this.

Fuck off about adding it to the layout theres no space you bellends

People want it though - Can google do it easily?

**Comment by benjimarshall** [comment]
Client side search at here: http://jekyll.tips/tutorials/search/

**Comment by benjimarshall** [comment]
@ChilliByte If you give me a UI, I'll write the searchy bit. Probably something along the lines of the current post displaying system, but with a search box at the top, perhaps where the category title currently is

**Comment by benjimarshall** [comment]
@ChilliByte And for goodness sake don't do anything unless you know it works. We now have regular visitors and we don't want to scare them off

**Comment by ChilliByte** [comment]
If you show me how to pull, edit **_VIEW**_ and push, I can start writing

I'm not adding huge UI changes on a live site with viewers

As for where the search box'll go, I'll think about it.

**Comment by ir-g** [comment]
Firstly, think about what viewers do and don't want. Search is useful, but not vital. Secondly, don't forget that I have used Jekyll a lot - I often know shortcuts with things like this, and know limitations. Client-side search makes sense when you don't have more than 100 posts/pages.

**Comment by ir-g** [comment]
How many posts do we have now out of interest?

**Comment by benjimarshall** [comment]
@isaacrg 30. I understand the search feature, all I need is a place to put it and a box for it

**Comment by ChilliByte** [comment]
i dont think search is necessary right now, as google seems to be able to find posts

**Comment by ir-g** [comment]
Absolutely - I agree
