### ISSUE TITLE
Standardise/Standardize names

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#61]
(See what I did there?)

Sometimes, names are just "Ciaran Hanvey"
At other times, they're "Ciaran Hanvey, Editor in Chief"

Make them all the latter.

**Comment by ir-g** [comment]
Maybe de-title them all, as I suggested, back in #34 (omg almost saw this coming or something). We could have shortcide for each author and then use Jekyll collections to create different pages for each author...

**Comment by ChilliByte** [comment]
@isaacrg I think we have a good (well ok) (fine barely working) system for the authors, if we just make all the author names pretty it'll be okay

**Comment by benjimarshall** [comment]
I agree with stripping them of their titles. It will just make it so much easier

**Comment by ChilliByte** [comment]
@benjimarshall if I set up all the author sites, can you standardise their names?

**Comment by ChilliByte** [comment]
I dont see the difference De-Titling makes, if anything it makes it harder as you have to store which people have what job but I'm the minority here, go ahead

**Comment by ir-g** [comment]
_alert_ I'm working on an author system right now - This will support neater auto-generation of author pages and names.

**Comment by ir-g** [comment]
Also, the de-titling takes into account that people wont permanently hold their roles...

**Comment by ChilliByte** [comment]
All Detitled (unless I've missed one)
