### ISSUE TITLE
Set up author websites (beta implementation)

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#63]
Set up author pages for:
- [x] Livvy (Teal)
- [x] Shannon (#330033)
- [x] Kane (Hot Pink)
- [x] Griffo ("Juicy Orange") Apparently

**Comment by ir-g** [comment]
@ChilliByte I'm working on an author page system right now - So you might want to hold off for now..

**Comment by ChilliByte** [comment]
@isaacrg Will it break the current one? seeing as currently its only ~10 lines of code per author, and people want to see results. Will it be okay if I set them up on the current system, then we silently port it over to yours if yours works well?

**Comment by ir-g** [comment]
@ChilliByte It shouldnt break the current one,  though it would help if you could change the layout to be called `deepauthor` or something similar.

**Comment by ChilliByte** [comment]
okay

**Comment by ChilliByte** [comment]
@isaacrg done, how is your thing going?

**Comment by ir-g** [comment]
@ChilliByte Ok - I have a good idea of how things will be organised, but am going to spend more time on it, in light of you having something that will work for now. The eventual plan is for something that will even work with the formatter for selecting the author.

**Comment by ChilliByte** [comment]
Should we split this into 2 issues? 1 for this current get-it-done-asap implementation, and another for the long-term-stable edition?

**Comment by ir-g** [comment]
Yes, that sounds like a good idea.
