### ISSUE TITLE
Set up a more sustainable author page system

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#66]

**Comment by ChilliByte** [comment]
@isaacrg Progress?

**Comment by ir-g** [comment]
@chillibyte Coming along OK, hopefully releasing at some point tomorrow.

**Comment by ir-g** [comment]
While authors still need adding(#79), the listing system works. See http://backchat.kefw.org/authors/hanveyc/ for example. Additionally, authors are now given as arrays - eventually authors will be listed by name and linked as needed.

**Comment by ChilliByte** [comment]
can the authors not be auto generated from _posts?

**Comment by ChilliByte** [comment]
also, what are the advantages/features of this new system, so we know how to use it properly - currently only you @isaacrg understand it (as is common when people write their own code I suppose XD)

**Comment by ir-g** [comment]
@ChilliByte Author pages sadly cannot be auto generated from posts.

The use of `_authors`(a [Jekyll collection](https://jekyllrb.com/docs/collections/)) adds data to `site.authors`, meaning that the bylines are capable of accessing more data about authors, and (eventually)each post can just use author shortcodes for referring to authors, and the bylines will automatically list each author, link to them, and so forth.

**Comment by ir-g** [comment]
Issue sorted. :smile:
