### ISSUE TITLE
Add new article marker

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#67]

**Comment by ir-g** [comment]
@ChilliByte What do you mean by this?

**Comment by ChilliByte** [comment]
Pav suggested adding a small bit of text saying "NEW" to articles that are part of the most recent edition

This would be green, in Raleway, just to the left of the "Read More" in the small article preview

**Comment by ir-g** [comment]
@ChilliByte Thats sounds good. How about linking it to the date of publication somehow?
ie. It starts fading away after 7 days and disappears after 14 days?

**Comment by ChilliByte** [comment]
Thats exactly what I was thinking - if it was released <1 month ago, show, else hide
