### ISSUE TITLE
Add edition value to each post

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#68]
Should we add an edition variable to the front matter of all of the posts, so we can generate individual edition pages at a later date?

**Comment by ChilliByte** [comment]
This is a very good idea, and should be coupled with #67 
ALSO DIBS NEXT ISSUE

**Comment by ChilliByte** [comment]
Can this not be done with a simple lookup table of when each edition was released?

**Comment by ir-g** [comment]
@ChilliByte I guess, but it would be less reliable, and less useful when taking into account the fact that in the future, article publication could be staggered.

**Comment by benjimarshall** [comment]
I'll write a tiny python script to do this. Shouldn't take long

**Comment by ir-g** [comment]
Awesome, use `edition: 1` in the post metadata.

**Comment by benjimarshall** [comment]
@isaacrg I was torn between using a tag and a completely custom field such as `edition` Should I use `edition` then?

**Comment by ir-g** [comment]
Use `edition`, as we then get to run numerical comparisons more easily.
