### ISSUE TITLE
Go Back button on each article

### ISSUE THREAD

**Issue by benjimarshall** [Kefwmag/kefwmag.github.io#7]
Make the Go Back buttons point to the relevant section, preferably with the name of the section. Also, make the magazine title at the top link back to home

**Comment by ChilliByte** [comment]
The back buttons go to the previous page, if a specific category is required, it can be accessed throught the menu. Is this not satisfactory?

**Comment by ir-g** [comment]
Benji's suggestion works, but might involve some fiddling with Jekyll - I can do that tommorow if anyone wants it?

**Comment by benjimarshall** [comment]
Go for it @isaacrg. Can I ask that you do it on a separate branch? Deep isn't too comfortable around them and I'd rather not have stuff broken on the master branch.

**Comment by ir-g** [comment]
Sure

**Comment by ir-g** [comment]
@benjimarshall With the introduction of the section and site titles being links([at my fork](http://ir-g.uk/kefwmag.github.io/sports/2016/02/08/sport-post-1.html)), I would argue that the "Go Back" button is useless. What are your thoughts?

**Comment by benjimarshall** [comment]
That sounds good, getting rid of the go back button. Could you have a look at the fairly funky CSS that the headers now seem to be displaying on your fork?

**Comment by ir-g** [comment]
@benjimarshall Sure, though name what changes you want(eg remove underline, change color to blue) so I get the changes right

**Comment by benjimarshall** [comment]
Removing the underline would be nice. The change of background of the header is the main thing: [here](http://ir-g.uk/kefwmag.github.io/news/) the background behind the text "News" is a grey colour when I would like it to be a red colour white text. I'll make a separate issue to address all of the CSS

**Comment by ir-g** [comment]
@benjimarshall Cool, thanks

**Comment by benjimarshall** [comment]
See [this issue](16) @isaacrg

**Comment by ir-g** [comment]
@benjimarshall Thanks!
