### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#72]
[Travis](https://travis-ci.org/Kefwmag/kefwmag.github.io/) is throwing some interesting HTML validation errors. If we are to persist with using `htmlproofer` for testing, then we need to see what we can do.

FYI - For easily understandable validation, look at the [W3 Validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Fbackchat.kefw.org%2Fama%2F2016%2F04%2F21%2Ffighting-with-parents%2Findex.html).

**Comment by ChilliByte** [comment]
Combined with #75, we've eradicated the errors.

They were, in order of frequency
- Unencoded & - now encoded
- Empty alt tags - now either contain {{include.description}} or " "
- 404 for @hexaglow's link - Changed to matt's twitter
- 404 for Sef's souncloud - Removed as he changes his soundcloud username more than he changes underwear

**Comment by benjimarshall** [comment]
@ChilliByte For the `<alt>` tags we actually use the `--empty-alt-ignore` flag with `html-proofer`. `<alt>` tags aren't are not a major issue for us so I just disabled the checking. Some `<alt>` tags are actually empty, I removed the space at the end

**Comment by ChilliByte** [comment]
the empty alt ignore returned 0 when i tried it, but okay
