### ISSUE TITLE
EITHER Encode all & as &amp; or get Travis to ignore them.

### ISSUE THREAD

**Issue by ChilliByte** [Kefwmag/kefwmag.github.io#75]
Travis shows about 72 identical errors, all pointing to this line:

`<li><a href="/arts/">Arts & Entertainment</a></li>`

or the "Mel & Ma" line.

The reason its throwing an error is because & is a special character in HTML, used for special entities - untypeable characters, for example the less that sign, &lt;, which is encoded as `&lt;`

Normally just using & in text is more than fine people wont care, but Travis does, and as such we should either encode them all as &amp; : `&amp;` or tell travis to shut up about them, as it thinks all the & in our copy is the start of an unfinished HTML entity.

**Comment by ChilliByte** [comment]
I'm leaning towards encode, seeing as we'd have to go through all the posts too and thats effort

**Comment by benjimarshall** [comment]
Well, `html-proofer` is moaning about them for a reason, so I would recommend fixing it if we can

**Comment by ChilliByte** [comment]
right okay, @benjimarshall can you maybe write some python to do the posts, while I sort out the other 2?

**Comment by benjimarshall** [comment]
@ChilliByte Where are the bits that need changing?

**Comment by ChilliByte** [comment]
@benjimarshall never mind, encoding the 2 that i mentioned at the start removed the other encoding errors, now we just have 2.

**Comment by ChilliByte** [comment]
Fixed as of last commit
