### ISSUE TITLE
Article categories

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#8]
@ChilliByte, will each article have only one category? I need to know for the improved version I'm making at [isaacrg/kefwmag.github.io](https://github.com/isaacrg/kefwmag.github.io), which I will eventually PR in. (Or you could give me edit access plz)

**Comment by benjimarshall** [comment]
It will only be in one major category such as Sport or Technology. Subcategories would be cool but if they can't be done, don't sweat it

**Comment by benjimarshall** [comment]
By the way, thanks for your help

**Comment by ir-g** [comment]
@benjimarshall No problem! I'll try to complete the fix tomorrow with an end aim of having a reasonable fix tomorrow(a few if statements in Jekyll), alongside any relevant changes to the underlying html, JS and CSS.

A different font on the site might be nice, and an about page and a contact form probably wouldn't hurt being on the site. These could be added to Github issues, though it's not for me to say on that.

**Comment by benjimarshall** [comment]
A Contact page, certainly. The font should be Raleway, which is was the editors voted for, and they decided they wanted the same font for both titles and text

**Comment by ChilliByte** [comment]
Thank you! Is this issue still necessary? The Categories seem to be working.

**Comment by ir-g** [comment]
@ChilliByte No it isn't, but a "contact page" issue should be created
