### ISSUE TITLE
Sort out byline, make include.

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#80]
For #62, #66.

**Comment by ChilliByte** [comment]
the byline code is more or less in place, it needs a little modifying, as the old urls were firstname-surname while your system is surnamefirstinitial but aside from that its ok

**Comment by ir-g** [comment]
Closed, sorted, even uses pretty urls. Re: #62, 66.
_Did not use include, for operational reasons._
