### ISSUE TITLE
Get rid of background badge?

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#84]
@benjimarshall @ChilliByte 

Should we get rid of the background badge, as it is mainly covered most of the time, or at least re-locate it?

**Comment by ChilliByte** [comment]
I like it where it is - its easily viewable on desktops

May consider adding a media query for mobiles to remove, though

**Comment by ir-g** [comment]
Fair enough, that sounds reasonable.

**Comment by ChilliByte** [comment]
Merging with #81 for a total overhaul of mobile/tablet views
