### ISSUE TITLE
Post previews scroll

### ISSUE THREAD

**Issue by ir-g** [Kefwmag/kefwmag.github.io#89]
Some post previews scroll (like "struggles with sadness")

**Comment by ChilliByte** [comment]
i cant seem to replicate this issue - on what device was this?

**Comment by ChilliByte** [comment]
all articles have this code:

```
main div article summary p {
    height:100%;
    overflow:hidden;
}
```

they are literally told not to scroll, so this is very weird

**Comment by ChilliByte** [comment]
ok this scrolling bug happens on desktop when scrolling diagonally - that is, both axes simultaneously

**Comment by ChilliByte** [comment]
misclick - this will be fixed when another issue is fixed - will create then reference
